services:
  postgres:
    image: postgres:15-alpine
    container_name: CCI-oms-postgres
    restart: always
    environment:
      POSTGRES_DB: oms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: CCI-oms-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no

volumes:
  postgres_data:
