
# Application Name
spring.application.name=OMS

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/oms_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}

# Hibernate & JPA Configuration
spring.jpa.hibernate.ddl-auto=update